# Generated by Django 4.2.29 on 2026-04-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='IMC'),
        ),
        migrations.AddField(
            model_name='profile',
            name='masa_muscular_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masa Muscular (kg)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='perimetro_cintura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cintura (cm)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='porcentaje_grasa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% Grasa'),
        ),
    ]
