# Generated by Django 4.2.29 on 2026-04-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_profile_imc_profile_masa_muscular_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='perimetro_cintura',
        ),
        migrations.AddField(
            model_name='profile',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones del Admin'),
        ),
    ]
