# Generated by Django 4.2.29 on 2026-04-14 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0004_remove_profile_imc_remove_profile_perimetro_cintura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('talla_cm', models.PositiveSmallIntegerField(verbose_name='Talla (cm)')),
                ('porcentaje_grasa', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='% Grasa')),
                ('masa_muscular_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Masa Muscular (kg)')),
                ('observaciones', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación Física',
                'verbose_name_plural': 'Evaluaciones Físicas',
                'ordering': ['-fecha'],
            },
        ),
    ]
